apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec: 
  nodeSelector:
    node_name: worker_node110  
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
