---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    elastic-app: elasticsearch
  name: elasticsearch-master
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      elastic-app: elasticsearch
  template:
    metadata:
      labels:
        elastic-app: elasticsearch
    spec:
      containers:
        - name: elasticsearch-master
          # image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
          image: docker.xsy.io/base/es:5.5.1
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "sysctl -w vm.max_map_count=262144; ulimit -l unlimited;"]
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          env:
            #- name: "discovery.type"
            #  value: "single-node"
            #- name: "bootstrap.memory_lock"
            #  value: "true"
            #- name: "discovery.zen.ping.unicast.hosts"
            #  value: "elasticsearch-discovery"
            #- name: "discovery.zen.minimum_master_nodes"
            #  value: "2"
            #- name: "discovery.zen.ping_timeout"
            #  value: "5s"
            #- name: "node.master"
            #  value: "true"
            #- name: "node.data"
            #  value: "false"
            # - name: "node.ingest"
            #  value: "false"
            - name: "ES_JAVA_OPTS"
              value: "-Xms256m -Xmx256m"

---
kind: Service
apiVersion: v1
metadata:
  labels:
    elastic-app: elasticsearch
  name: elasticsearch-discovery
spec:
  ports:
    - port: 9300
      targetPort: 9300
  selector:
    elastic-app: elasticsearch

