apiVersion: v1
kind: Service
metadata:
  name: test-nginx-svc
  # namespace: kube-system
spec:
  selector:
    k8s-app: test-nginx
  clusterIP: 10.96.2.2
  ports:
    - port: 80

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  # namespace: kube-system
  labels:
    k8s-app: test-nginx
spec:
  replicas: 2
  template:
    metadata:
      name:  nginx-pod
      namespace: kube-system
      labels:
        k8s-app: test-nginx
    spec:
      containers:
        - name: nginx
          image: image.service.ob.local:5000/nginx:latest
